/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 scene.gltf 
Author: avilezfernando2009 (https://sketchfab.com/avilezfernando2009)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spongebob-squarepants-custom-model-016aa8df34e946faa02a145bdabe4b48
Title: spongebob squarepants custom model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[0, -250, 0]} scale={20}>
          <mesh geometry={nodes.spongebob_chr_sb05_png_0.geometry} material={materials.chr_sb05_png} />
          <mesh geometry={nodes.spongebob_Material_2002_0.geometry} material={materials['Material_2.002']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
